export enum NfStatus {
  RECEIVED = 'RECEIVED',
  XML_VALIDATED = 'XML_VALIDATED',
  XML_ERROR = 'XML_ERROR',
  BUSINESS_VALIDATED = 'BUSINESS_VALIDATED',
  BUSINESS_ERROR = 'BUSINESS_ERROR',
  PERSISTED = 'PERSISTED',
  PERSISTENCE_ERROR = 'PERSISTENCE_ERROR',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
