apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nf-processor-ingress
  namespace: nf-processor
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: nf-processor.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nf-processor-service
                port:
                  number: 80
