apiVersion: v1
kind: Secret
metadata:
  name: nf-processor-secrets
  namespace: nf-processor
type: Opaque
stringData:
  DB_USERNAME: "REPLACE_ME"
  DB_PASSWORD: "REPLACE_ME"
  REDIS_PASSWORD: "REPLACE_ME"
  RABBITMQ_USERNAME: "REPLACE_ME"
  RABBITMQ_PASSWORD: "REPLACE_ME"
  S3_ACCESS_KEY: "REPLACE_ME"
  S3_SECRET_KEY: "REPLACE_ME"
  S3_ENDPOINT: "REPLACE_ME"
  JWT_SECRET: "REPLACE_ME"
