import { ExternalInvoiceOperation } from '../enums/external-invoice-operation.enum';

const CFOP_OPERATION_MAP: Record<string, ExternalInvoiceOperation> = {
  '5101': ExternalInvoiceOperation.VENDA,
  '5102': ExternalInvoiceOperation.VENDA,
  '5103': ExternalInvoiceOperation.VENDA,
  '5104': ExternalInvoiceOperation.VENDA,
  '5105': ExternalInvoiceOperation.VENDA,
  '5106': ExternalInvoiceOperation.VENDA,
  '5109': ExternalInvoiceOperation.VENDA,
  '5110': ExternalInvoiceOperation.VENDA,
  '5111': ExternalInvoiceOperation.VENDA,
  '5112': ExternalInvoiceOperation.VENDA,
  '5113': ExternalInvoiceOperation.VENDA,
  '5114': ExternalInvoiceOperation.VENDA,
  '5115': ExternalInvoiceOperation.VENDA,
  '5116': ExternalInvoiceOperation.VENDA,
  '5117': ExternalInvoiceOperation.VENDA,
  '5118': ExternalInvoiceOperation.VENDA,
  '5119': ExternalInvoiceOperation.VENDA,
  '5120': ExternalInvoiceOperation.VENDA,
  '5122': ExternalInvoiceOperation.VENDA,
  '5123': ExternalInvoiceOperation.VENDA,
  '5124': ExternalInvoiceOperation.VENDA,
  '5125': ExternalInvoiceOperation.VENDA,
  '5401': ExternalInvoiceOperation.VENDA,
  '5402': ExternalInvoiceOperation.VENDA,
  '5403': ExternalInvoiceOperation.VENDA,
  '5405': ExternalInvoiceOperation.VENDA,
  '6101': ExternalInvoiceOperation.VENDA,
  '6102': ExternalInvoiceOperation.VENDA,
  '6103': ExternalInvoiceOperation.VENDA,
  '6104': ExternalInvoiceOperation.VENDA,
  '6105': ExternalInvoiceOperation.VENDA,
  '6106': ExternalInvoiceOperation.VENDA,
  '6107': ExternalInvoiceOperation.VENDA,
  '6108': ExternalInvoiceOperation.VENDA,
  '6109': ExternalInvoiceOperation.VENDA,
  '6110': ExternalInvoiceOperation.VENDA,
  '6111': ExternalInvoiceOperation.VENDA,
  '6112': ExternalInvoiceOperation.VENDA,
  '6113': ExternalInvoiceOperation.VENDA,
  '6114': ExternalInvoiceOperation.VENDA,
  '6115': ExternalInvoiceOperation.VENDA,
  '6116': ExternalInvoiceOperation.VENDA,
  '6117': ExternalInvoiceOperation.VENDA,
  '6118': ExternalInvoiceOperation.VENDA,
  '6119': ExternalInvoiceOperation.VENDA,
  '6120': ExternalInvoiceOperation.VENDA,
  '6122': ExternalInvoiceOperation.VENDA,
  '6123': ExternalInvoiceOperation.VENDA,
  '6124': ExternalInvoiceOperation.VENDA,
  '6125': ExternalInvoiceOperation.VENDA,
  '6401': ExternalInvoiceOperation.VENDA,
  '6402': ExternalInvoiceOperation.VENDA,
  '6403': ExternalInvoiceOperation.VENDA,
  '6404': ExternalInvoiceOperation.VENDA,
  '6405': ExternalInvoiceOperation.VENDA,

  '1201': ExternalInvoiceOperation.DEVOLUCAO,
  '1202': ExternalInvoiceOperation.DEVOLUCAO,
  '1203': ExternalInvoiceOperation.DEVOLUCAO,
  '1204': ExternalInvoiceOperation.DEVOLUCAO,
  '1208': ExternalInvoiceOperation.DEVOLUCAO,
  '1209': ExternalInvoiceOperation.DEVOLUCAO,
  '1410': ExternalInvoiceOperation.DEVOLUCAO,
  '1411': ExternalInvoiceOperation.DEVOLUCAO,
  '1503': ExternalInvoiceOperation.DEVOLUCAO,
  '1504': ExternalInvoiceOperation.DEVOLUCAO,
  '1553': ExternalInvoiceOperation.DEVOLUCAO,
  '1660': ExternalInvoiceOperation.DEVOLUCAO,
  '2201': ExternalInvoiceOperation.DEVOLUCAO,
  '2202': ExternalInvoiceOperation.DEVOLUCAO,
  '2203': ExternalInvoiceOperation.DEVOLUCAO,
  '2204': ExternalInvoiceOperation.DEVOLUCAO,
  '2208': ExternalInvoiceOperation.DEVOLUCAO,
  '2209': ExternalInvoiceOperation.DEVOLUCAO,
  '2410': ExternalInvoiceOperation.DEVOLUCAO,
  '2411': ExternalInvoiceOperation.DEVOLUCAO,
  '2503': ExternalInvoiceOperation.DEVOLUCAO,
  '2504': ExternalInvoiceOperation.DEVOLUCAO,
  '2553': ExternalInvoiceOperation.DEVOLUCAO,
  '2660': ExternalInvoiceOperation.DEVOLUCAO,
  '5201': ExternalInvoiceOperation.DEVOLUCAO,
  '5202': ExternalInvoiceOperation.DEVOLUCAO,
  '5208': ExternalInvoiceOperation.DEVOLUCAO,
  '5209': ExternalInvoiceOperation.DEVOLUCAO,
  '5410': ExternalInvoiceOperation.DEVOLUCAO,
  '5411': ExternalInvoiceOperation.DEVOLUCAO,
  '5412': ExternalInvoiceOperation.DEVOLUCAO,
  '5413': ExternalInvoiceOperation.DEVOLUCAO,
  '5503': ExternalInvoiceOperation.DEVOLUCAO,
  '5553': ExternalInvoiceOperation.DEVOLUCAO,
  '5555': ExternalInvoiceOperation.DEVOLUCAO,
  '5660': ExternalInvoiceOperation.DEVOLUCAO,
  '6201': ExternalInvoiceOperation.DEVOLUCAO,
  '6202': ExternalInvoiceOperation.DEVOLUCAO,
  '6208': ExternalInvoiceOperation.DEVOLUCAO,
  '6209': ExternalInvoiceOperation.DEVOLUCAO,
  '6410': ExternalInvoiceOperation.DEVOLUCAO,
  '6411': ExternalInvoiceOperation.DEVOLUCAO,
  '6412': ExternalInvoiceOperation.DEVOLUCAO,
  '6413': ExternalInvoiceOperation.DEVOLUCAO,
  '6503': ExternalInvoiceOperation.DEVOLUCAO,
  '6553': ExternalInvoiceOperation.DEVOLUCAO,
  '6555': ExternalInvoiceOperation.DEVOLUCAO,
  '6660': ExternalInvoiceOperation.DEVOLUCAO,

  '1101': ExternalInvoiceOperation.COMPRA,
  '1102': ExternalInvoiceOperation.COMPRA,
  '2101': ExternalInvoiceOperation.COMPRA,
  '2102': ExternalInvoiceOperation.COMPRA,

  '5151': ExternalInvoiceOperation.TRANSFERENCIA,
  '5152': ExternalInvoiceOperation.TRANSFERENCIA,
  '5153': ExternalInvoiceOperation.TRANSFERENCIA,
  '5155': ExternalInvoiceOperation.TRANSFERENCIA,
  '5156': ExternalInvoiceOperation.TRANSFERENCIA,
  '5157': ExternalInvoiceOperation.TRANSFERENCIA,
  '6151': ExternalInvoiceOperation.TRANSFERENCIA,
  '6152': ExternalInvoiceOperation.TRANSFERENCIA,
  '6153': ExternalInvoiceOperation.TRANSFERENCIA,
  '6155': ExternalInvoiceOperation.TRANSFERENCIA,
  '6156': ExternalInvoiceOperation.TRANSFERENCIA,
  '6157': ExternalInvoiceOperation.TRANSFERENCIA,

  '5901': ExternalInvoiceOperation.REMESSA,
  '5902': ExternalInvoiceOperation.REMESSA,
  '5903': ExternalInvoiceOperation.REMESSA,
  '5904': ExternalInvoiceOperation.REMESSA,
  '5905': ExternalInvoiceOperation.REMESSA,
  '5906': ExternalInvoiceOperation.REMESSA,
  '5907': ExternalInvoiceOperation.REMESSA,
  '5908': ExternalInvoiceOperation.REMESSA,
  '5909': ExternalInvoiceOperation.REMESSA,
  '5910': ExternalInvoiceOperation.REMESSA,
  '5911': ExternalInvoiceOperation.REMESSA,
  '6901': ExternalInvoiceOperation.REMESSA,
  '6902': ExternalInvoiceOperation.REMESSA,
  '6903': ExternalInvoiceOperation.REMESSA,
  '6904': ExternalInvoiceOperation.REMESSA,
  '6905': ExternalInvoiceOperation.REMESSA,
  '6906': ExternalInvoiceOperation.REMESSA,
  '6907': ExternalInvoiceOperation.REMESSA,
  '6908': ExternalInvoiceOperation.REMESSA,
  '6909': ExternalInvoiceOperation.REMESSA,
  '6910': ExternalInvoiceOperation.REMESSA,
  '6911': ExternalInvoiceOperation.REMESSA,

};

export function cfopToOperation(cfop: string): ExternalInvoiceOperation {
  return CFOP_OPERATION_MAP[cfop] ?? ExternalInvoiceOperation.VENDA;
}

export function isDevolucao(operation: ExternalInvoiceOperation): boolean {
  return operation === ExternalInvoiceOperation.DEVOLUCAO;
}

export function isProcessableOperation(operation: ExternalInvoiceOperation): boolean {
  return (
    operation === ExternalInvoiceOperation.VENDA ||
    operation === ExternalInvoiceOperation.DEVOLUCAO
  );
}

export function isDevolucaoAssignDefault(cfop: string): boolean {
  return cfop.startsWith('1') || cfop.startsWith('2');
}
